# Site settings
title:       Notes
description: On life and/with tech
url:         "https://jurf.github.io"

# Personal info
author: Juraj Fiala
email:  jurajfiala+github@pm.me

# Other accounts
twitter_username: juraj_fiala
github_username:  jurf
disqus:
  shortname:      doctorjellyface # Cannot be changed

# Build settings
#paginate: 5
timezone:  Europe/Bratislava
permalink: pretty
theme:     minima
# markdown:  CommonMarkGhPages
commonmark:
  options: ["SMART", "STRIKETHROUGH_DOUBLE_TILDE", "UNSAFE"]
  extensions: ["strikethrough", "autolink"]

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - README.md

text:
  post:
    minute_read:    'minute read'
